/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login_gonzalo_hugo;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author FP
 */
public class Frame extends javax.swing.JFrame {
    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
        setTitle("Inicio de sesión en SQL");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBanda = new javax.swing.JPanel();
        jPanelContenido = new javax.swing.JPanel();
        jLogin = new javax.swing.JLabel();
        jUsuario = new javax.swing.JLabel();
        jUsuarioField = new javax.swing.JTextField();
        jContrasena = new javax.swing.JLabel();
        jContrasenaField = new javax.swing.JPasswordField();
        jCrearUsuario = new javax.swing.JButton();
        jAccederUsuario = new javax.swing.JButton();
        jReestablecerContrasena = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio de Sesión en SQL");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelBanda.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanelBandaLayout = new javax.swing.GroupLayout(jPanelBanda);
        jPanelBanda.setLayout(jPanelBandaLayout);
        jPanelBandaLayout.setHorizontalGroup(
            jPanelBandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        jPanelBandaLayout.setVerticalGroup(
            jPanelBandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelBanda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 630));

        jLogin.setBackground(new java.awt.Color(255, 204, 255));
        jLogin.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jLogin.setText("LOGIN");
        jLogin.setOpaque(true);

        jUsuario.setBackground(new java.awt.Color(255, 204, 255));
        jUsuario.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jUsuario.setText("USUARIO");
        jUsuario.setAlignmentX(0.5F);
        jUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jUsuario.setOpaque(true);
        jUsuario.setPreferredSize(new java.awt.Dimension(70, 35));

        jContrasena.setBackground(new java.awt.Color(255, 204, 255));
        jContrasena.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jContrasena.setText("CONTRASEÑA");
        jContrasena.setOpaque(true);
        jContrasena.setPreferredSize(new java.awt.Dimension(70, 35));

        jContrasenaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jContrasenaFieldActionPerformed(evt);
            }
        });

        jCrearUsuario.setBackground(new java.awt.Color(0, 0, 0));
        jCrearUsuario.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jCrearUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jCrearUsuario.setText("CREAR USUARIO");
        jCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCrearUsuarioActionPerformed(evt);
            }
        });

        jAccederUsuario.setBackground(new java.awt.Color(0, 0, 0));
        jAccederUsuario.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jAccederUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jAccederUsuario.setText("ACCEDER USUARIO");

        jReestablecerContrasena.setBackground(new java.awt.Color(0, 0, 0));
        jReestablecerContrasena.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jReestablecerContrasena.setForeground(new java.awt.Color(255, 255, 255));
        jReestablecerContrasena.setText("REESTABLECER CONTRASEÑA");

        javax.swing.GroupLayout jPanelContenidoLayout = new javax.swing.GroupLayout(jPanelContenido);
        jPanelContenido.setLayout(jPanelContenidoLayout);
        jPanelContenidoLayout.setHorizontalGroup(
            jPanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContenidoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jAccederUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(361, 361, 361))
                    .addGroup(jPanelContenidoLayout.createSequentialGroup()
                        .addGroup(jPanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jUsuarioField, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jContrasenaField, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jReestablecerContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelContenidoLayout.createSequentialGroup()
                        .addGroup(jPanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLogin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelContenidoLayout.setVerticalGroup(
            jPanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContenidoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jUsuarioField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jContrasenaField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jCrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jAccederUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jReestablecerContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 390, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jContrasenaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jContrasenaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jContrasenaFieldActionPerformed

    private void jCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCrearUsuarioActionPerformed
        if (jContrasenaField == null || jContrasenaField == null) {
            JOptionPane.showMessageDialog(this, "Debes de rellenar todos los campos para crear el usuario", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {

        }

    }//GEN-LAST:event_jCrearUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAccederUsuario;
    private javax.swing.JLabel jContrasena;
    private javax.swing.JPasswordField jContrasenaField;
    private javax.swing.JButton jCrearUsuario;
    private javax.swing.JLabel jLogin;
    private javax.swing.JPanel jPanelBanda;
    private javax.swing.JPanel jPanelContenido;
    private javax.swing.JButton jReestablecerContrasena;
    private javax.swing.JLabel jUsuario;
    private javax.swing.JTextField jUsuarioField;
    // End of variables declaration//GEN-END:variables

}
