/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hugo_ruleta;

/**
 *
 * @author FP
 */
public class Frame extends javax.swing.JFrame {
    
    dialogo d1;
    Frame2 f1;

    /**
     * Creates new form Frame
     */
    public Frame() {
        
        initComponents();
        setTitle("Inicio de sesión en Casino Online");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jUsuario = new javax.swing.JLabel();
        jCrearUsuario = new javax.swing.JButton();
        jContrasena = new javax.swing.JLabel();
        jContrasenaField = new javax.swing.JPasswordField();
        jUsuarioField = new javax.swing.JTextField();
        jAccederUsuario = new javax.swing.JButton();
        jUsuario1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jContrasena1 = new javax.swing.JLabel();
        jUsuarioField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jUsuario.setBackground(new java.awt.Color(0, 153, 153));
        jUsuario.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jUsuario.setText("              USUARIO");
        jUsuario.setAlignmentX(0.5F);
        jUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jUsuario.setOpaque(true);
        jUsuario.setPreferredSize(new java.awt.Dimension(70, 35));

        jCrearUsuario.setBackground(new java.awt.Color(0, 0, 0));
        jCrearUsuario.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jCrearUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jCrearUsuario.setText("CREAR NUEVO USUARIO");
        jCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCrearUsuarioActionPerformed(evt);
            }
        });

        jContrasena.setBackground(new java.awt.Color(0, 153, 153));
        jContrasena.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jContrasena.setText("            CONTRASEÑA");
        jContrasena.setOpaque(true);
        jContrasena.setPreferredSize(new java.awt.Dimension(70, 35));

        jContrasenaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jContrasenaFieldActionPerformed(evt);
            }
        });

        jUsuarioField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUsuarioFieldActionPerformed(evt);
            }
        });

        jAccederUsuario.setBackground(new java.awt.Color(0, 0, 0));
        jAccederUsuario.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jAccederUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jAccederUsuario.setText("ACCEDER CON EL USUARIO");
        jAccederUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAccederUsuarioActionPerformed(evt);
            }
        });

        jUsuario1.setBackground(new java.awt.Color(0, 153, 153));
        jUsuario1.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jUsuario1.setText("  ¿NO TIENES CUENTA?");
        jUsuario1.setAlignmentX(0.5F);
        jUsuario1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jUsuario1.setOpaque(true);
        jUsuario1.setPreferredSize(new java.awt.Dimension(70, 35));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hugo_ruleta/Casino2.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        jContrasena1.setBackground(new java.awt.Color(0, 153, 153));
        jContrasena1.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jContrasena1.setText("  DINERO QUE INGRESARÁS HOY");
        jContrasena1.setOpaque(true);
        jContrasena1.setPreferredSize(new java.awt.Dimension(70, 35));

        jUsuarioField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUsuarioField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jAccederUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jContrasenaField, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jUsuarioField, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jContrasena1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jUsuarioField1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCrearUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jUsuario1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                    .addComponent(jUsuario1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jUsuarioField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jContrasenaField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jContrasena1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jUsuarioField1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jAccederUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jUsuarioFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUsuarioFieldActionPerformed
        jUsuarioField.setText("");
    }//GEN-LAST:event_jUsuarioFieldActionPerformed

    private void jContrasenaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jContrasenaFieldActionPerformed
        jContrasenaField.setText("");
    }//GEN-LAST:event_jContrasenaFieldActionPerformed

    private void jCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCrearUsuarioActionPerformed
        d1 = new dialogo(this, true);
        d1.ponerNombre(jUsuarioField.getText().toString());
    }//GEN-LAST:event_jCrearUsuarioActionPerformed

    private void jAccederUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAccederUsuarioActionPerformed
        f1 = new Frame2();
        f1.ponerNombre(jUsuarioField.getText().toString());
        f1.ponerDinero(jUsuarioField1.getText().toString());
    }//GEN-LAST:event_jAccederUsuarioActionPerformed

    private void jUsuarioField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUsuarioField1ActionPerformed
        jUsuarioField1.setText("");
    }//GEN-LAST:event_jUsuarioField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAccederUsuario;
    private javax.swing.JLabel jContrasena;
    private javax.swing.JLabel jContrasena1;
    private javax.swing.JPasswordField jContrasenaField;
    private javax.swing.JButton jCrearUsuario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jUsuario;
    private javax.swing.JLabel jUsuario1;
    private javax.swing.JTextField jUsuarioField;
    private javax.swing.JTextField jUsuarioField1;
    // End of variables declaration//GEN-END:variables
}
