/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hugo_ruleta;

/**
 *
 * @author FP
 */
public class Frame2 extends javax.swing.JFrame {

    private boolean ganado = true;

    /**
     * Creates new form Frame2
     */
    public Frame2() {
        initComponents();
        setVisible(true);
    }

    public void ponerNombre(String nombre) {
        jUsuario4.setText(nombre);
    }

    public void ponerDinero(String nombre) {
        jUsuario5.setText(nombre);
    }

    public void generarNumero(String color) {
        int numeroGanador = (int) (Math.random() * 36);

        if (color == "rojo" && numeroGanador % 2 == 0 || color == "negro" && numeroGanador % 2 != 0) {
            ganado = true;
            String dineroApostadoTexto = jTextArea1.getText();
            int dineroRestante = Integer.parseInt(jUsuario5.getText());
            int dineroApostado = Integer.parseInt(dineroApostadoTexto);
            int dineroGanado = dineroApostado * 2;
            String numeroGanadorTexto = Integer.toString(numeroGanador);
            jTextArea2.setText("El número premiado ha sido el " + numeroGanadorTexto + "\n");
            jTextArea2.append("Has ganado: " + dineroGanado + " €");
            dineroRestante = dineroRestante + dineroApostado;
            jTextArea1.setText("");
            jTextArea1.setText(Integer.toString(dineroRestante));

        } else {
            String dineroApostadoTexto = jTextArea1.getText();
            int dineroRestante = Integer.parseInt(jUsuario5.getText());
            int dineroApostado = Integer.parseInt(dineroApostadoTexto);
            String numeroGanadorTexto = Integer.toString(numeroGanador);
            jTextArea2.setText("El número premiado ha sido el " + numeroGanadorTexto + "\n");
            ganado = false;
            jTextArea2.append("Lo siemto, has perido el dinero apostado\n");
            dineroRestante = dineroRestante - dineroApostado;
            jTextArea1.setText("");
            jTextArea1.setText(Integer.toString(dineroRestante));

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jUsuario = new javax.swing.JLabel();
        jUsuario1 = new javax.swing.JLabel();
        jAccederUsuario = new javax.swing.JButton();
        jAccederUsuario1 = new javax.swing.JButton();
        jAccederUsuario2 = new javax.swing.JButton();
        jAccederUsuario3 = new javax.swing.JButton();
        jAccederUsuario4 = new javax.swing.JButton();
        jAccederUsuario5 = new javax.swing.JButton();
        jUsuario2 = new javax.swing.JLabel();
        jUsuario3 = new javax.swing.JLabel();
        jUsuario4 = new javax.swing.JLabel();
        jUsuario5 = new javax.swing.JLabel();
        jTextArea1 = new javax.swing.JTextArea();
        jTextArea2 = new javax.swing.JTextArea();
        jAccederUsuario6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("A jugar!!");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\FP\\Documents\\NetBeansProjects\\Hugo_Ruleta\\img\\Ruleta3.jpg")); // NOI18N
        jLabel1.setText("jLabel1");

        jUsuario.setBackground(new java.awt.Color(255, 255, 255));
        jUsuario.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jUsuario.setText("USUARIO:");
        jUsuario.setAlignmentX(0.5F);
        jUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jUsuario.setOpaque(true);
        jUsuario.setPreferredSize(new java.awt.Dimension(70, 35));

        jUsuario1.setBackground(new java.awt.Color(255, 255, 255));
        jUsuario1.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jUsuario1.setText("DINERO:");
        jUsuario1.setAlignmentX(0.5F);
        jUsuario1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jUsuario1.setOpaque(true);
        jUsuario1.setPreferredSize(new java.awt.Dimension(70, 35));

        jAccederUsuario.setBackground(new java.awt.Color(0, 0, 0));
        jAccederUsuario.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jAccederUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jAccederUsuario.setText("ROJO");
        jAccederUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAccederUsuarioActionPerformed(evt);
            }
        });

        jAccederUsuario1.setBackground(new java.awt.Color(0, 0, 0));
        jAccederUsuario1.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jAccederUsuario1.setForeground(new java.awt.Color(255, 255, 255));
        jAccederUsuario1.setText("NEGRO");
        jAccederUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAccederUsuario1ActionPerformed(evt);
            }
        });

        jAccederUsuario2.setBackground(new java.awt.Color(0, 0, 0));
        jAccederUsuario2.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jAccederUsuario2.setForeground(new java.awt.Color(255, 255, 255));
        jAccederUsuario2.setText("1 - 12");
        jAccederUsuario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAccederUsuario2ActionPerformed(evt);
            }
        });

        jAccederUsuario3.setBackground(new java.awt.Color(0, 0, 0));
        jAccederUsuario3.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jAccederUsuario3.setForeground(new java.awt.Color(255, 255, 255));
        jAccederUsuario3.setText("13 -24");
        jAccederUsuario3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAccederUsuario3ActionPerformed(evt);
            }
        });

        jAccederUsuario4.setBackground(new java.awt.Color(0, 0, 0));
        jAccederUsuario4.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jAccederUsuario4.setForeground(new java.awt.Color(255, 255, 255));
        jAccederUsuario4.setText("25-36");
        jAccederUsuario4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAccederUsuario4ActionPerformed(evt);
            }
        });

        jAccederUsuario5.setBackground(new java.awt.Color(0, 0, 0));
        jAccederUsuario5.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jAccederUsuario5.setForeground(new java.awt.Color(255, 255, 255));
        jAccederUsuario5.setText("NÚMERO:");
        jAccederUsuario5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAccederUsuario5ActionPerformed(evt);
            }
        });

        jUsuario2.setBackground(new java.awt.Color(255, 255, 255));
        jUsuario2.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jUsuario2.setText("APUESTA:");
        jUsuario2.setAlignmentX(0.5F);
        jUsuario2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jUsuario2.setOpaque(true);
        jUsuario2.setPreferredSize(new java.awt.Dimension(70, 35));

        jUsuario3.setBackground(new java.awt.Color(255, 255, 255));
        jUsuario3.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jUsuario3.setText("APUESTAS DISPONIBLES AHORA:");
        jUsuario3.setAlignmentX(0.5F);
        jUsuario3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jUsuario3.setOpaque(true);
        jUsuario3.setPreferredSize(new java.awt.Dimension(70, 35));

        jUsuario4.setBackground(new java.awt.Color(255, 255, 255));
        jUsuario4.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jUsuario4.setAlignmentX(0.5F);
        jUsuario4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jUsuario4.setOpaque(true);
        jUsuario4.setPreferredSize(new java.awt.Dimension(70, 35));

        jUsuario5.setBackground(new java.awt.Color(255, 255, 255));
        jUsuario5.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jUsuario5.setAlignmentX(0.5F);
        jUsuario5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jUsuario5.setOpaque(true);
        jUsuario5.setPreferredSize(new java.awt.Dimension(70, 35));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);

        jAccederUsuario6.setBackground(new java.awt.Color(0, 0, 0));
        jAccederUsuario6.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jAccederUsuario6.setForeground(new java.awt.Color(255, 255, 255));
        jAccederUsuario6.setText("X SALIR X");
        jAccederUsuario6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAccederUsuario6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jAccederUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jAccederUsuario1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jAccederUsuario2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jAccederUsuario4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jAccederUsuario5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jAccederUsuario3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextArea2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jAccederUsuario6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jUsuario2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(jTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jUsuario4, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jUsuario5, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(jUsuario3, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jUsuario2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jUsuario4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jUsuario5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jUsuario3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jAccederUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jAccederUsuario1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jAccederUsuario2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jAccederUsuario3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jAccederUsuario4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jAccederUsuario5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextArea2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jAccederUsuario6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        jTextArea1.getAccessibleContext().setAccessibleParent(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAccederUsuario5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAccederUsuario5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAccederUsuario5ActionPerformed

    private void jAccederUsuario4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAccederUsuario4ActionPerformed
    }//GEN-LAST:event_jAccederUsuario4ActionPerformed

    private void jAccederUsuario3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAccederUsuario3ActionPerformed
    }//GEN-LAST:event_jAccederUsuario3ActionPerformed

    private void jAccederUsuario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAccederUsuario2ActionPerformed
    }//GEN-LAST:event_jAccederUsuario2ActionPerformed

    private void jAccederUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAccederUsuario1ActionPerformed
        generarNumero("negro");
    }//GEN-LAST:event_jAccederUsuario1ActionPerformed

    private void jAccederUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAccederUsuarioActionPerformed
        generarNumero("rojo");
    }//GEN-LAST:event_jAccederUsuarioActionPerformed

    private void jAccederUsuario6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAccederUsuario6ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jAccederUsuario6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAccederUsuario;
    private javax.swing.JButton jAccederUsuario1;
    private javax.swing.JButton jAccederUsuario2;
    private javax.swing.JButton jAccederUsuario3;
    private javax.swing.JButton jAccederUsuario4;
    private javax.swing.JButton jAccederUsuario5;
    private javax.swing.JButton jAccederUsuario6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel jUsuario;
    private javax.swing.JLabel jUsuario1;
    private javax.swing.JLabel jUsuario2;
    private javax.swing.JLabel jUsuario3;
    private javax.swing.JLabel jUsuario4;
    private javax.swing.JLabel jUsuario5;
    // End of variables declaration//GEN-END:variables
}
